include("shared.lua")

include("client/state.lua")

include("client/derma/frame_panel.lua")
include("client/derma/frame_pointer.lua")
include("client/derma/keyframe_settings.lua")
include("client/derma/load.lua")
include("client/derma/motionpaths.lua")
include("client/derma/physrecord.lua")
include("client/derma/properties.lua")
include("client/derma/save.lua")
include("client/derma/settings.lua")
include("client/derma/smh_menu.lua")
include("client/derma/spawn.lua")
include("client/derma/tooltip.lua")
include("client/derma/world_clicker.lua")
include("client/derma/audioclip_pointer.lua")
include("client/derma/audioclip_tools.lua")
include("client/derma/audioclip_insert.lua")
include("client/derma/audioseq_save.lua")
include("client/derma/audioseq_load.lua")

include("client/derma/audioclip_pointer.lua")
include("client/derma/audioclip_tools.lua")
include("client/derma/audioclip_insert.lua")
include("client/derma/audioseq_save.lua")
include("client/derma/audioseq_load.lua")

include("client/concommands.lua")
include("client/controller.lua")
include("client/highlighter.lua")
include("client/physrecord.lua")
include("client/renderer.lua")
include("client/settings.lua")
include("client/ui.lua")
include("client/audioclip.lua")
include("client/audioclip_data.lua")
include("client/audioclip_manager.lua")
